# Generated by Django 2.2.12 on 2024-12-18 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentreponse',
            options={'verbose_name': 'Student Response', 'verbose_name_plural': 'Student Responses'},
        ),
        migrations.RemoveField(
            model_name='studentreponse',
            name='is_True',
        ),
        migrations.AlterField(
            model_name='studentreponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reponses', to='quiz.Question'),
        ),
        migrations.AlterField(
            model_name='studentreponse',
            name='reponse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentreponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reponses', to='student.Student'),
        ),
    ]
