# Generated by Django 2.2.12 on 2024-12-28 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_classe_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matiere',
            options={'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='Description de la filière', null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('niveaux', models.ManyToManyField(blank=True, related_name='filiere_niveaux', to='school.Niveau')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_filiere', to='school.Filiere'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_filiere', to='school.Filiere'),
        ),
    ]
