# Generated by Django 2.2.12 on 2024-12-18 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_instructor_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code de la matière')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='instructor.Instructor')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_instructors', to='instructor.Subject')),
            ],
            options={
                'verbose_name': 'Affectation de matière',
                'verbose_name_plural': 'Affectations de matières',
                'unique_together': {('instructor', 'subject')},
            },
        ),
    ]
