# Generated by Django 2.2.12 on 2024-12-18 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_cours_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0006_instructorsubject_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationMatiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_matieres', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_instructors', to='school.Matiere')),
            ],
            options={
                'verbose_name': 'Affectation de Matière',
                'verbose_name_plural': 'Affectations de Matières',
            },
        ),
        migrations.DeleteModel(
            name='InstructorSubject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
