# Generated by Django 2.2.12 on 2024-12-18 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_auto_20241218_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectationmatiere',
            options={},
        ),
        migrations.AlterField(
            model_name='affectationmatiere',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='instructor.Instructor'),
        ),
        migrations.AlterField(
            model_name='affectationmatiere',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='school.Matiere'),
        ),
    ]
